services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: unless-stopped
    volumes:
      - /opt/devdistro/data/mongodb:/data/db
    networks:
      - devdistro-internal

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - /opt/devdistro/data/redis:/data
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - devdistro-internal

networks:
  devdistro-internal:
    name: devdistro-internal
    driver: bridge
